# Generated by Django 5.0 on 2023-12-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.IntegerField()),
                ('ciclo', models.IntegerField(null=True)),
                ('foto', models.FileField(null=True, upload_to='usuarios/perfiles')),
                ('fechreg', models.DateTimeField(null=True)),
                ('fechupdt', models.DateTimeField(null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('lugar', models.CharField(max_length=150)),
                ('destinatario', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=30)),
                ('voucher', models.FileField(upload_to='usuarios/vouchers')),
                ('fechreg', models.DateField(null=True)),
                ('state', models.IntegerField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='formatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='usuarios/portafolio')),
                ('fechreg', models.DateField()),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='repositorio/formatos')),
                ('nombre', models.CharField(max_length=50)),
                ('fechareg', models.DateField()),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitud')),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
