# Generated by Django 5.0 on 2023-12-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_ciclo_alter_usuario_fechreg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='state',
            new_name='estado',
        ),
    ]
