# Generated by Django 3.2.8 on 2024-01-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240105_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='cod',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
