# Generated by Django 3.2.8 on 2024-01-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_docs_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='fechareg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
