# Generated by Django 3.2.8 on 2024-01-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_formatos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
