# Generated by Django 3.2.8 on 2024-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activity_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20)),
                ('razon', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=50)),
                ('representante', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=30)),
            ],
        ),
    ]
